services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_GRAPHQL_GRAPHIQL_ENABLED: false
    ports:
      - "8080:8080"

  db:
    ports: 
      - "5432:5432"