spring.application.name=match-me
spring.datasource.url=jdbc:postgresql://localhost:5432/matchme
spring.datasource.username=postgres
spring.datasource.password=8ded6076
spring.datasource.driver-class-name=org.postgresql.Driver
# convenient in development, in production preferably 'validate' or migrations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
# JWT keys path
jwt.public.key.path=file:../JWT-keys/public.key
jwt.private.key.path=file:../JWT-keys/private.key
# profile picture upload path
app.upload-dir=uploads/avatars
app.upload-url-prefix=/uploads/avatars
spring.servlet.multipart.max-file-size=2000KB
spring.servlet.multipart.max-request-size=2000KB
frontendUrl=http://localhost:5173
